name: Test
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-android:
      runs-on: macos-latest
      steps:
        - name: run e2e tests
          uses: reactivecircus/android-emulator-runner@v2
            with:
              api-level: 29
              profile: Nexus 6
              script: avdmanager list device
